### ISSUE TITLE
Service Request by Donrie Purcell to repair download bug

### ISSUE THREAD

**Issue by donriepurcell** [dlounsbu/NYHEALing-IPAtracker-support#11]
- [ ] Qualtrics Service Request Form was received from User
- [ ] e-mail acknowledging that User's Qualtrics Service Request Form was sent
- [ ] Problem NOT RESOLVED
- [ ] Problem PARTIALLY RESOLVED 
- [x] Problem FULLY RESOLVED and Issue is Closed
- [ ] Qualtrics Post-Service Request Survey was sent to User

Use comments feature (below) to document:

1. A clear and concise description of the solution.

2. A clear and concise description of any alternative solutions or features you've considered.

3. Any additional context, such as screenshots about the problem.

**Comment by donriepurcell** [comment]
Hi Jeff
 
Please note the following bug related to the downloads feature of the IPA Tracker.
 
When downloading Venues, they are still coming across as Locations in the download (excel files).
 
Regards
Donrie Purcell, PhD, MPH
 
Every generation has the obligation to free men's minds for a look at new worlds,....to look out from a higher plateau than the last generation.
Ellison S. Onizuka 


CONFIDENTIALITY: This email (including any attachments) may contain confidential, proprietary and/or privileged information. Any duplication, copying, distribution, dissemination, transmission, disclosure or use in any manner of this email (including any attachments) without the authorization of the sender is strictly prohibited. If you receive this email (including any attachments) in error, please notify the sender and delete this email (including any attachments) from your system. Thank you.

**Comment by donriepurcell** [comment]
Jeff Bazinet <jbazinet@northcountryinitiative.org>
To: Donrie Purcell <donrie.purcell@einsteinmed.org>; david lounsbury <david.lounsbury@einsteinmed.org>; Nicholas Bove <nicholas.bove@einsteinmed.org>

This is resolved but won’t be deployed until later today with the other enhancements.

**Comment by donriepurcell** [comment]
From: Jeff Bazinet <jbazinet@northcountryinitiative.org>
Date: Monday, August 16, 2021 at 8:31 AM
To: Donrie Purcell <donrie.purcell@einsteinmed.org>
Cc: david lounsbury <david.lounsbury@einsteinmed.org>, Nicholas Bove <nicholas.bove@einsteinmed.org>
Subject: RE: IPA Download Bugs
CAUTION: This email comes from an external source; the attachments and/or links may compromise our secure environment. Do not open or click on suspicious emails. Please click on the “Phish Alert” button on the top right of the Outlook dashboard to report any suspicious emails.

This is resolved but won’t be deployed until later today with the other enhancements.

**Comment by dlounsbu** [comment]
![IPA LOCATION VENUE label](https://user-images.githubusercontent.com/20574023/129904512-356b5384-f447-481f-a615-ad75a83c04fc.JPG)

As of Aug 18, this bug still remains. I will follow up with Jeff!

**Comment by dlounsbu** [comment]
Hi @jbazinet1111 

See comment above about the LOCATIONS label needing to be updated to VENUES. Thanks

**Comment by dlounsbu** [comment]
This has been fixed! Thanks @jbazinet1111

**Comment by donriepurcell** [comment]
Hi jeff, 

While Resources work in some smart strategies and and not in others. I reported that it is up and running to RC's at the HCS level. Please anything you can do to check on this urgently I would greatly appreciate it.

Donrie

**Comment by jbazinet1111** [comment]
Depends on the data. I can't really debug these without some kind of screenshot and county/ila/strategy info
________________________________

**Comment by donriepurcell** [comment]
Hi jeff,
I sent you an email with the  screen shots.

**Comment by jbazinet1111** [comment]
You should be all set now. Thanks for the screenshots
